// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExmTh9tHEEcTk5HVH0Bq_e_OWLs1G3gc',
    appId: '1:93748883359:android:4a11f26efe2c71f48dd7aa',
    messagingSenderId: '93748883359',
    projectId: 'nabard-hackathon',
    databaseURL: 'https://nabard-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nabard-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_WbjzmmFJr-adIMZmLE4Vgf45PJbTqg',
    appId: '1:93748883359:ios:5effe40a84e2c7058dd7aa',
    messagingSenderId: '93748883359',
    projectId: 'nabard-hackathon',
    databaseURL: 'https://nabard-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nabard-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.nabard',
  );
}
